# Generated by Django 5.1.6 on 2025-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
    ]
